name: utilities
description: A new Flutter package project.
version: 0.0.1
homepage: SinaMN75.com
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.15
  get: ^4.6.3
  package_info_plus: ^1.4.2
  share_plus: ^4.0.3
  file_picker: ^4.5.1
  intl: ^0.17.0
  webviewx: ^0.2.1
  get_storage: ^2.0.3
  flutter_svg: ^1.0.3
  persian_tools: ^1.0.1
  group_button: ^5.0.1
  logger: ^1.1.0
  image_cropper: ^2.0.2
  cached_network_image: ^3.2.0
  video_player: ^2.4.2
  just_audio: ^0.9.21
  syncfusion_flutter_pdfviewer: ^20.1.55-beta
  path_provider: ^2.0.10
  flutter_downloader: ^1.7.4
  flutter_local_notifications: ^9.5.2
#  firebase_messaging: ^11.2.12
#  firebase_core: ^1.14.0
#  firebase_auth: ^3.3.13
#  google_sign_in: ^5.2.4

flutter:
  uses-material-design: true
  assets:
    - lib/assets/data/