name: utilities
description: A Flutter package supported by ahmad panahi.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.15
  get: ^4.6.3
  package_info_plus: ^4.1.0
  share_plus: ^4.0.3
  file_picker: ^5.2.8
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  persian_tools: ^1.0.1
  group_button: ^5.0.1
  logger: ^2.0.1
  image_cropper: ^5.0.0
  cached_network_image: ^3.2.0
  path_provider: ^2.1.4
  flutter_local_notifications: ^9.5.2
  dio: ^5.1.1
  dio_smart_retry: ^5.0.0

flutter:
  uses-material-design: true
